apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/elasticsearch"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
        ports:
        - containerPort: 9200   # HTTP API для Elasticsearch
          name: http            # Имя порта для HTTP API
        - containerPort: 9300   # Транспортный порт для кластера
          name: transport       # Имя порта для транспортного протокола
        env:
        - name: discovery.type
          value: "single-node"  # Запуск Elasticsearch в однородном режиме
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"  # Ограничение памяти для JVM
        volumeMounts:
        - name: elasticsearch-storage
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: elasticsearch-storage
        persistentVolumeClaim:
          claimName: elasticsearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      name: http
    - protocol: TCP
      port: 9300
      targetPort: 9300
      name: transport
  type: NodePort
