apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/neo4j"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:4.4
        ports:
        - containerPort: 7474   # Порт для HTTP-интерфейса Neo4j (Browser)
        - containerPort: 7687   # Порт для Bolt-протокола (для взаимодействия с базой через драйвера)
        env:
        - name: NEO4J_AUTH      # Задаем пользователя и пароль для входа
          value: "neo4j/password123"
        volumeMounts:
        - name: neo4j-storage
          mountPath: /data
      volumes:
      - name: neo4j-storage
        persistentVolumeClaim:
          claimName: neo4j-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  selector:
    app: neo4j
  ports:
    - protocol: TCP
      name: neo4j
      port: 7474
      targetPort: 7474
    - protocol: TCP
      name: bolt
      port: 7687
      targetPort: 7687
  type: NodePort